LOG_LEVEL: "debug"
LOG_PATH: "./Logs/"
CAMUNDAS:
  #First Camunda
  - URL: "https://catfact.ninja/fact"
    User: "testUser"
    Password: "password"
  #Second Camunda
  - URL: "https://catfact.ninja/fact"
    User: "anotherTestUser"
    Password: "drowssap"